<?php include('settings.php');if(function_exists('add_theme_support')){add_theme_support('menus');}function get_category_id($cat_name){$term=get_term_by('name',$cat_name,'category');return $term->term_id;}if(function_exists('add_theme_support')){add_theme_support('post-thumbnails');add_image_size('slide-image',976,600,true);add_image_size('home-post-wide',470,317,true);add_image_size('home-post-tall',227,317,true);add_image_size('home-post-box',244,258,true);add_image_size('blog-image',614,337,true);}if(function_exists('register_sidebar')){register_sidebar(array('name'=>'Sidebar','before_widget'=>'<div class="side_box">','after_widget'=>'</div>','before_title'=>'<h3 class="side_title">','after_title'=>'</h3>',));}add_filter('pre_get_posts','query_post_type');function query_post_type($query){if(is_category()||is_tag()){$post_type=get_query_var('post_type');if($post_type)$post_type=$post_type;else $post_type=array('post','seo');$query->set('post_type',$post_type);return $query;}}function my_search_form($form){$form='<form role="search" method="get" id="searchform" class="searchform" action="'.home_url('/').'" >
    <div><label class="screen-reader-text" for="s">'.__('Search for:').'</label>
    <input type="text" value="'.get_search_query().'" name="s" id="s" />
    <input type="submit" id="searchsubmit" value="'.esc_attr__('Search').'" />
    </div>
    </form>';return $form;}add_filter('get_search_form','my_search_form');function catch_that_image(){global $post,$posts;$first_img='';ob_start();ob_end_clean();$output=preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i',$post->post_content,$matches);$first_img=$matches[1][0];if(empty($first_img)){$first_img="/images/post_default.png";}return $first_img;}function ds_get_excerpt($num_chars){$temp_str=substr(strip_tags(get_the_content()),0,$num_chars);$temp_parts=explode(" ",$temp_str);$temp_parts[(count($temp_parts)-1)]='';if(strlen(strip_tags(get_the_content()))>125)return implode(" ",$temp_parts).'...';else return implode(" ",$temp_parts);}function ds_get_excerpt2($num_chars,$post_link){$temp_str=substr(strip_tags(get_the_content()),0,$num_chars);$temp_parts=explode(" ",$temp_str);$temp_parts[(count($temp_parts)-1)]='';if(strlen(strip_tags(get_the_content()))>125)return implode(" ",$temp_parts).'<a href="'.$post_link.'">[read more ...]</a>';else return implode(" ",$temp_parts);}class template1_search extends WP_Widget{function template1_search(){parent::WP_Widget(false,'Template 1 Search');}function widget($args,$instance){$args['search_title']=$instance['search_title'];t1_func_search($args);}function update($new_instance,$old_instance){return $new_instance;}function form($instance){$search_title=esc_attr($instance['search_title']);?>
                <p><label for="<?php echo $this->get_field_id('search_title');?>"><?php _e('Title:');?> <input class="widefat" id="<?php echo $this->get_field_id('search_title');?>" name="<?php echo $this->get_field_name('search_title');?>" type="text" value="<?php echo $search_title;?>" /></label></p>
<?php
 }}function t1_func_search($args=array(),$displayComments=TRUE,$interval=''){global $wpdb;echo $args['before_widget'];if($args['search_title']!='')echo $args['before_title'].$args['search_title'].$args['after_title'];?>
        <div class="t1_search_cont">
            <form role="search" method="get" id="searchform" action="<?php echo home_url('/');?>">
            <input type="text" name="s" id="s" />
            <INPUT TYPE="image" SRC="<?php bloginfo('stylesheet_directory');?>/images/search-icon.jpg" class="t1_search_icon" BORDER="0" ALT="Submit Form">
            </form>
        </div><!--//t1_search_cont-->
        <?php
 echo $args['after_widget'];wp_reset_query();}register_widget('template1_search');$prefix='ex_';$meta_box=array('id'=>'my-meta-box','title'=>'Custom meta box','page'=>'post','context'=>'normal','priority'=>'high','fields'=>array(array('name'=>'Show in slideshow','id'=>$prefix.'show_in_slideshow','type'=>'checkbox')));add_action('admin_menu','mytheme_add_box');function mytheme_add_box(){global $meta_box;add_meta_box($meta_box['id'],$meta_box['title'],'mytheme_show_box',$meta_box['page'],$meta_box['context'],$meta_box['priority']);}function mytheme_show_box(){global $meta_box,$post;echo '<input type="hidden" name="mytheme_meta_box_nonce" value="',wp_create_nonce(basename(__FILE__)),'" />';echo '<table class="form-table">';foreach($meta_box['fields'] as $field){$meta=get_post_meta($post->ID,$field['id'],true);echo '<tr>','<th style="width:20%"><label for="',$field['id'],'">',$field['name'],'</label></th>','<td>';switch($field['type']){case 'text':echo '<input type="text" name="',$field['id'],'" id="',$field['id'],'" value="',$meta?$meta:$field['std'],'" size="30" style="width:97%" />','<br />',$field['desc'];break;case 'textarea':echo '<textarea name="',$field['id'],'" id="',$field['id'],'" cols="60" rows="4" style="width:97%">',$meta?$meta:$field['std'],'</textarea>','<br />',$field['desc'];break;case 'select':echo '<select name="',$field['id'],'" id="',$field['id'],'">';foreach($field['options'] as $option){echo '<option',$meta==$option?' selected="selected"':'','>',$option,'</option>';}echo '</select>';break;case 'radio':foreach($field['options'] as $option){echo '<input type="radio" name="',$field['id'],'" value="',$option['value'],'"',$meta==$option['value']?' checked="checked"':'',' />',$option['name'];}break;case 'checkbox':echo '<input type="checkbox" value="Yes" name="',$field['id'],'" id="',$field['id'],'"',$meta?' checked="checked"':'',' />';break;}echo '<td>','</tr>';}echo '</table>';}add_action('save_post','mytheme_save_data');function mytheme_save_data($post_id){global $meta_box;if(!wp_verify_nonce($_POST['mytheme_meta_box_nonce'],basename(__FILE__))){return $post_id;}if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE){return $post_id;}if('page'==$_POST['post_type']){if(!current_user_can('edit_page',$post_id)){return $post_id;}}elseif(!current_user_can('edit_post',$post_id)){return $post_id;}foreach($meta_box['fields'] as $field){$old=get_post_meta($post_id,$field['id'],true);$new=$_POST[$field['id']];if($new&&$new!=$old){update_post_meta($post_id,$field['id'],$new);}elseif(''==$new&&$old){delete_post_meta($post_id,$field['id'],$old);}}}?>
<?php register_nav_menu(gora,gora_bkvsky);?>
<?php register_nav_menu(dol,dol_bkvsky);?>
<?php register_nav_menu(iphone,iphony_bkvsky);?>
<?php register_nav_menu(dol_dolny,dol_dolny_bkvsky);?>
<?php function pagination($pages='',$range=1){$showitems=($range*2)+1;global $paged;if(empty($paged))$paged=1;if($pages==''){global $wp_query;$pages=$wp_query->max_num_pages;if(!$pages){$pages=1;}}if(1!=$pages){echo "<div class=\"pagination\"><span>".$paged." of ".$pages."</span>";if($paged>2&&$paged>$range+1&&$showitems<$pages)echo "<a href='".get_pagenum_link(1)."' class=\"pag_first\" ></a>";if($paged>1&&$showitems<$pages)echo "<a href='".get_pagenum_link($paged-1)."' class=\"pag_prev\"></a>";for($i=1;$i<=$pages;$i++){if(1!=$pages&&(!($i>=$paged+$range+1||$i<=$paged-$range-1)||$pages<=$showitems)){echo ($paged==$i)?"<span class=\"current\">".$i."</span>":"<a href='".get_pagenum_link($i)."' class=\"inactive\">".$i."</a>";}}if($paged<$pages&&$showitems<$pages)echo "<a href=\"".get_pagenum_link($paged+1)."\"  class=\"pag_next\"></a>";if($paged<$pages-1&&$paged+$range-1<$pages&&$showitems<$pages)echo "<a href='".get_pagenum_link($pages)."'  class=\"pag_last\"></a>";echo "</div>\n";}}?>

<?php add_action( 'amp_init', 'xyz_amp_add_review_cpt' );
  function xyz_amp_add_review_cpt() {
      add_post_type_support( 'seo', AMP_QUERY_VAR );
      add_post_type_support( 'Venues', AMP_QUERY_VAR );
      add_post_type_support( 'Destination', AMP_QUERY_VAR );
      add_post_type_support( 'Style', AMP_QUERY_VAR );
      add_post_type_support( 'galleries', AMP_QUERY_VAR);
      add_post_type_support( 'Gallery', AMP_QUERY_VAR);
      add_post_type_support( 'gallery', AMP_QUERY_VAR);
  } ?>
